blog/urls.py
from django.urls import path

from blog.feeds import LatestPostsFeed
from blog.views import post_list, PostDetail, post_detail, post_share, search, redisearch, redirect_to_post_detail

app_name = 'blog'

urlpatterns = [
    path('<int:year>/<int:month>/<int:day>/<slug:post_slug>/', post_detail, name='post_detail'),
    path('post/<int:post_id>/', redirect_to_post_detail, name='redirect_to_post_detail'),
    path('', post_list, name='post_list'),
    path('search/', search, name='search'),
    path('redisearch/', redisearch, name='redisearch'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed')
]

django_blog/urls.py
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    # the sitemap
    path('sitemap.xml',
         sitemap,
         {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from pprint import pprint
from random import randint

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from faker import Faker
from redisearch import Client
from taggit.managers import TaggableManager

fakegen = Faker()

STATUS_CHOICES = (
    ('draft', 'Draft'),
    ('published', 'Published'),
)


class PublishedQuerySet(models.Manager):
    def get_queryset(self):
        return super(PublishedQuerySet, self).get_queryset().filter(status='published')


class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField(default=fakegen.text)
    publish = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedQuerySet()

    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    @staticmethod
    def before_save(sender, instance, **kwargs):
        print('pre_save')
        pprint(instance.status)
        if instance.status == 'published':
            if instance.pk is None:
                instance.publish = timezone.now()
            else:
                post = Post.objects.get(pk=instance.pk)
                if post.status == 'draft':
                    #     print('bbb')
                    instance.publish = timezone.now()

    def save(self, *args, **kwargs):
        pprint('save')
        slug_str = self.title
        self.slug = slugify(slug_str)

        super().save(*args, **kwargs)

    @staticmethod
    def after_save(sender, instance, *args, **kwargs):
        print('post_save')
        try:
            # Creating a client with a given index name
            client = Client('blog_index')

            # Indexing a document
            document = client.add_document(instance.id, title=instance.title, body=instance.body)
            pprint('document')
            pprint(document)
        except Exception as e:
            pprint(e)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.created.year,
                                                 self.created.strftime('%m'),
                                                 self.created.strftime('%d'),
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from pprint import pprint

from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, DetailView
from elasticsearch_dsl.query import MultiMatch, Q as elastic_Q
from redisearch import Client
from taggit.models import Tag

from blog.documents import PostDocument
from blog.forms import EmailPostForm, CommentForm, SearchForm
from blog.models import Post
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search


# from elasticsearch_dsl import connections
#
# # Elasticsearch_dsl
# connections.create_connection(hosts=['localhost'], timeout=20)


# class PostList(ListView):
#     template_name = 'blog/post/list.html'
#     # model = Post
#     queryset = Post.published.all()
#     paginate_by = 5

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 10)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag
                   })


class PostDetail(DetailView):
    model = Post


def post_detail(request, year, month, day, post_slug):
    post = Post.objects.filter(slug=post_slug, status='published')[0]
    print('post')
    print(post.publish)
    post = get_object_or_404(Post, slug=post_slug,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             )

    comments = post.comments.filter(active=True)
    comment_added = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            comment_added = True
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request=request, template_name='blog/post/detail.html', context={'post': post,
                                                                                   'comments': comments,
                                                                                   'comment_form': comment_form,
                                                                                   'comment_added': comment_added,
                                                                                   'similar_posts': similar_posts})


def redirect_to_post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    return redirect(post.get_absolute_url())


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cleaned_data["name"]} {cleaned_data["email"]}, recommends you reading {post.title} '
            message = f'read "{post.title}" at {post_url}\n\n\'s comments: {cleaned_data["comments"]}'
            send_mail(subject=subject, message=message, from_email='admin@email.com',
                      recipient_list=[cleaned_data['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request=request, template_name='blog/post/share.html', context={'post': post,
                                                                                  'form': form,
                                                                                  'sent': sent})


def search(request):
    client = Elasticsearch()

    s = Search(using=client)

    search_result = []
    # pprint(request.POST['query'])
    form = SearchForm(request.POST)
    if form.is_valid():
        # search_result = PostDocument.search().filter('match', )
        search_result = Search().using(client).query(
            elastic_Q('bool', must=[elastic_Q('match', title=request.POST['query'])]))
        for result in search_result:
            pprint(result.body)

    context = {
        'form': form,
        'search_result': search_result
    }
    return render(request=request, template_name='blog/search.html', context=context)


def redisearch(request):
    # TODO: This View Should be in AJAX mode
    # TODO: Implement Autocomplete Feature with Redisearch
    client = Client('blog_index')
    res = client.search("search engine")

    search_result = []
    # pprint(request.POST['query'])
    form = SearchForm(request.POST)
    if form.is_valid():
        # search_result = PostDocument.search().filter('match', )
        search_result = client.search(request.POST['query'])
        if len(search_result.docs) != 0:
            search_result = search_result.docs
        else:
            search_result = []

    context = {
        'form': form,
        'search_result': search_result
    }
    return render(request=request, template_name='blog/redisearch.html', context=context)

blog/templates/blog/base.html
<!DOCTYPE html>
{% load blog_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div id="content">
    {% block content %}

    {% endblock %}
    <div id="sidebar">
        <hr>
        <span>sidebar</span>
        <h2>My Blog</h2>
        <p>This is my blog.</p>
        <p>I've Written {% total_posts %} posts so far</p>
        {% show_latest_posts %}
        <p>
            <a href="{% url "blog:post_feed" %}">
                Subscribe to my RSS feed
            </a>
        </p>
        <hr>
        <h6>most commented posts</h6>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    <span>number of comments: {{ post.total_comments }}</span>
                </li>
            {% endfor %}

        </ul>
    </div>
</div>
</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        {#TODO: show multiple  page numbers instead of one. #}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/redisearch.html
{% extends 'blog/base.html' %}

{% block title %}
    Search By Redisearch
{% endblock %}

{% block content %}
    <h1>Search By Redisearch</h1>
    <form method="post" action="{% url 'blog:redisearch' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
    <h3>search result</h3>
    {% for result_item in search_result %}
        <h6>{{ result_item.title }}</h6>
        <p>{{ result_item.body|truncatewords:5 }}</p>
        <a href="{% url 'blog:redirect_to_post_detail' result_item.id %}">Go to</a>
    {% empty %}
        {% if request.method == 'POST' %}
            Sorry, No result!
        {% endif %}
    {% endfor %}
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}

{% block title %}
    Search Page
{% endblock %}

{% block content %}
    <h1>Search Page</h1>
    <form method="post" action="{% url 'blog:search' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
    <h3>search result</h3>
    {% for result_item in search_result %}
        <h6>{{ result_item.title }}</h6>
        <p>{{ result_item.body|truncatewords:5 }}</p>
    {% empty %}
        {% if request.method == 'POST' %}
            Sorry, No result!
        {% endif %}
    {% endfor %}

{% endblock %}